/**
 * Tipos de eventos da Central de Entradas (Sprint 8).
 *
 * @module motores/central-entradas/config/centralEventosTipos
 */

const TIPOS_EVENTO = Object.freeze({
  SYNC_INICIADA: 'SYNC_INICIADA',
  SYNC_CONCLUIDA: 'SYNC_CONCLUIDA',
  SYNC_ERRO: 'SYNC_ERRO',
  DOCUMENTO_RECEBIDO: 'DOCUMENTO_RECEBIDO',
  DOCUMENTO_PROCESSADO: 'DOCUMENTO_PROCESSADO',
  DOCUMENTO_ATUALIZADO: 'DOCUMENTO_ATUALIZADO',
  DOCUMENTO_MIGRADO: 'DOCUMENTO_MIGRADO',
  CIENCIA_ENVIADA: 'CIENCIA_ENVIADA',
  /** Claim atômico pré-envio (RC3.3.3) — não é evento de timeline de negócio. */
  MANIFESTACAO_CLAIM: 'MANIFESTACAO_CLAIM',
  MANIFESTACAO_ACEITA: 'MANIFESTACAO_ACEITA',
  MANIFESTACAO_REJEITADA: 'MANIFESTACAO_REJEITADA',
  CONSULTA_DFE_POS_MANIFESTACAO: 'CONSULTA_DFE_POS_MANIFESTACAO',
  PARSER_CONCLUIDO: 'PARSER_CONCLUIDO',
  MIIP_CONCLUIDO: 'MIIP_CONCLUIDO',
  COMPRA_GRAVADA: 'COMPRA_GRAVADA',
  ERRO: 'ERRO',
  CONFIG_ALTERADA: 'CONFIG_ALTERADA'
});

const ORIGENS = Object.freeze({
  BACKGROUND: 'background',
  MANUAL: 'manual',
  API: 'api',
  SISTEMA: 'sistema',
  ABRIR_CENTRAL: 'abrir_central',
  DIAGNOSTICO: 'diagnostico',
  UPLOAD: 'upload',
  COMPRAS: 'compras',
  MIGRACAO_RC65: 'MIGRACAO_RC65'
});

module.exports = {
  TIPOS_EVENTO,
  ORIGENS
};
